import 'dart:ui';

import 'package:get/get.dart';

class Lang extends Translations {
  static final putative = Locale("tr", "TR");
  static final languages = [
    Locale("tr", "TR"),
    Locale("en", "US")
  ];

  @override
  Map<String, Map<String, String>> get keys => {
    'en_US': {
      'en' : 'English',
      'tr' : 'Turkish',
      'name': 'Name - Surname',
      'nme' : 'Name',
      'sname' : 'Surname',
      'error' :' Error',
      'pname' : 'Pharmacy Name',
      'phone' : 'Phone Number' ,
      'id' : 'T.C. Identification number',
      'mail' : 'E-mail',
      'address' : 'Address',
      'settings' : 'Settings',
      'security' : 'Security' ,
      'psw' : 'Password, security, personal details' ,
      'pay' : 'Payment Methods',
      'payment' : 'Payment',
      'login' : 'Login',
      'lang' : 'Language',
      'help' : 'Help',
      'home page' : 'Home Page',
      'about' : 'About',
      'address and contact information' : 'Address and Contact Information',
      'amount' : 'Amount',
      'cancel' : 'Cancel',
      'card number' : 'Card Number',
      'card number cannot be blank' : 'Card number cannot be blank',
      'continue' : 'Continue',
      'country' : 'Country',
      'city' : 'City',
      'choose payment method' : 'Choose Payment Method',
      'ccard' : 'Credit Card / Debit Card',
      'card holder name' : 'Card Holder Name',
      'complete order' : 'Complete Order',
      'district' : 'District',
      'exit' : 'Log out',
      'expiry date' : 'Expiry Date (MM/YY)',
      'enter recipe number' : 'Enter Recipe Number',
      'enter your card information' : 'Enter Your Card Information',
      'enterId' : 'Enter TR Identity Number',
      'go back' : 'Go Back',
      'go forward' : 'Go Forward',
      'incoming orders' : 'Incoming Orders',
      'login error' : 'Login Error',
      'rregister' : 'Register',
      'register' : 'Register now',
      'rerror' : 'Register Error',
      'pay at the door' : 'Pay at the Door',
      'payy' : 'Pay',
      'pregister' : 'Pharmacist Registration',
      'pharmacist login' : 'Pharmacist Login',
      'password' : 'Password',
      'profile' : 'Profile',
      'prescription number' : 'Prescription Number',
      'or' : 'Or',
      'order page' : 'Order Page',
      'order' : 'Order',
      'btprofile' : 'Back To Profile',
      'btsettings' : 'Back To Settings',
      'support' : 'To Get Support',
      'select country' : 'Select Country',
      'select city' : 'Select City',
      'select district' : 'Select District',
      'select a pharmacy' : 'Select a Pharmacy',
      'sign up' : 'Sign Up',
      'successful' : 'Successful',
      'verify' : 'Verify',
      'validation error' : 'Validation Error',
      'verification code' : 'Verification Code',
      'verify phone' : 'Verify Phone',
      'info' : 'You can contact via jetilac@gmail.com or help.jetilac.com.',
      'about the app' : 'About the App',
      'big About' : 'Jetilac is an innovative mobile application developed to make healthcare services more accessible. Jetilac allows patients to easily order medicines from their homes. This application is used to securely transmit prescriptions to pharmacists and deliver medicines to your homes via couriers, while increasing patient satisfaction. Jetilaçs user-friendly interface and security measures ensure the protection of patients personal information and health data. All transactions are protected by encryption protocols and performed in accordance with privacy policies. Jetilaç provides great convenience for many patients, such as the elderly, those with limited mobility or those who cannot spare time for pharmacies due to intense work schedule. It can also handle special requests such as emergencies or regular drug deliveries for a predetermined time frame. Jetilac provides a safe, fast and user-friendly service to patients by bridging modern technology and the needs of the healthcare industry. Thanks to Jetilac, it is now much easier and safer to order medicines and forward prescriptions to pharmacists.',
      'pharmacy' : 'Pharmacy',
      'user login' : 'User Login',
      'warning' : 'Warning',
      'welcome' : 'Welcome!',
      'ifmp' : 'I forgot my password',
      'siwg' : 'Sign in with Google',
      'nam' : 'Not a member?',
      'twaeliwg' : 'There was an error logging in with Google.',
      'iuop' : 'Invalid username or password.',
      'lfu' : 'Login for Users',
      'lfp' : 'Login for Pharmacists',
      'pfiaf' : 'Please fill in all fields.',
      'ok' : 'Okey',
      'neighbourhood' : 'Neighbourhood',
      'select neighborhood' : 'Select Neighborhood',
      'street' : 'Street',
      'enter street name' : 'Enter Street Name',
      'apartment name' : 'Apartment Name',
      'enter apartment name' : 'Enter Apartment Name',
      'apartment no':'Apartment No',
      'enter apartment number' : 'Enter Apartment Number',
      'apartment number' : 'Apartment Number',
      'eenter apartment number' : 'Enter Apartment Number',
      'save' : 'Save',
      'peavpn' : 'Please enter a valid prescription number (must be 8 digits).',
      'peavidn' : 'Please enter a valid TR ID number (must be 11 digits).',
      'psccap' : 'Please select city, county and pharmacy.',
      'oaai' : 'Order and Address Information',
      'pcyoiitiamiti' : 'Please check your order information. If there is any mistake in the information, please go back to the previous page and update your information.',
      'peyfai' : 'Please enter your full address information.',
      'cnmbd' : 'Card number must be 16 digits',
      'chncbe' : 'Cardholder name cannot be empty!',
      'edcbe' : 'Expiry date cannot be empty!',
      'eavedmy' : 'Enter a valid expiration date (MM/YY)',
      'cvvcbe' : 'CVV cannot be empty!',
      'cvvmbetd' : 'CVV must be 3 digits!',
      'yohbsw' : 'Your order has been successfully executed.',
      'eapfcblb' : 'E-mail and password fields cannot be left blank.',
      'ahaa' : 'Already have an account?',
      'petvcstyp' : 'Please enter the verification code sent to your phone:',
      'pncblb' : 'Phone number cannot be left blank!',






    },
    'tr_TR': {
      'en' : 'İngilizce',
      'tr' : 'Türkçe',
      'name': 'Ad - Soyad',
      'nme' : 'Ad',
      'sname' : 'Soyad',
      'error' : 'Hata',
      'pname' : 'Eczane Adı',
      'phone' : 'Telefon Numarası' ,
      'id' : 'T.C. Kimlik Numarası',
      'mail' : 'E-posta',
      'address' : 'Adres',
      'settings' : 'Ayarlar',
      'security' : 'Güvenlik' ,
      'psw' : 'Şifre, güvenlik, kişisel detaylar' ,
      'pay' : 'Ödeme Yöntemleri',
      'payment' : 'Ödeme',
      'payy' : 'Öde',
      'lang' : 'Dil',
      'login' : 'Giriş Yap',
      'help' : 'Yardım',
      'home page' : 'Ana Sayfa',
      'address and contact information' : 'Adres ve İletişim Bilgileri',
      'about' : 'Hakkında',
      'amount' : 'Tutar',
      'cancel' : 'İptal',
      'card number' : 'Kart Numarası',
      'card number cannot be blank' : 'Kart numarası boş olamaz',
      'continue' : 'Devam',
      'country' : 'Ülke',
      'city' : 'Şehir',
      'choose payment method' : 'Ödeme Yöntemini Seçiniz',
      'ccard' : 'Kredi Kartı / Banka Kartı',
      'card holder name' : 'Kart Sahibi Adı',
      'complete order' : 'Siparişi Tamamla',
      'district' : 'İlçe',
      'exit' : 'Çıkış Yap',
      'enter recipe number' : 'Reçete Numarasını Girin',
      'enter your card information' : 'Kart Bilgilerinizi Giriniz',
      'enterId' : 'TC Kimlik Numarasını Girin',
      'expiry date' : 'Son Kullanma Tarihi (AA/YY)',
      'go back' : 'Geri Dön',
      'go forward' : 'İleri',
      'incoming orders' : 'Gelen Siparişler',
      'login error' : 'Giriş Hatası',
      'rregister' : 'Kayıt Ol',
      'register' : 'Şimdi üye ol',
      'rerror' : 'Kayıt Olma Hatası',
      'pay at the door' : 'Kapıda Ödeme',
      'pregister' : 'Eczacı Kayıt',
      'pharmacist login' : 'Eczacı Girişi',
      'password' : 'Şifre',
      'profile' : 'Profil',
      'prescription number' : 'Reçete Numarası',
      'or' : 'Veya',
      'order page' : 'Sipariş Sayfası',
      'order' : 'Sipariş Ver',
      'btprofile' : 'Profile Dön',
      'btsettings' : 'Ayarlara Dön',
      'support' : 'Destek Almak İçin',
      'select country' : 'Ülke Seçin',
      'select city' : 'Şehir Seçin',
      'select district' : 'İlçe Seçin',
      'select a pharmacy' : 'Eczane Seçin',
      'sign up' : 'Üye Ol',
      'successful' : 'Successful',
      'verify' : 'Doğrula',
      'validation error' : 'Doğrulama Hatası',
      'verification code' : 'Doğrulama Kodu',
      'verify phone' : 'Telefonu Doğrula',
      'info' : 'jetilac@gmail.com veya help.jetilac.com üzerinden iletişime geçebilirsiniz.',
      'about the app' : 'Uygulama Hakkında',
      'big About' : 'Jetilaç, sağlık hizmetlerini daha erişilebilir hale getirmek amacıyla geliştirilmiş yenilikçi bir mobil uygulamadır. Jetilaç, hastaların kolaylıkla evlerinden ilaç siparişi verebilmesine olanak sağlar. Bu uygulama, hasta memnuniyetini artırırken, reçeteleri güvenli bir şekilde eczacılara iletmek ve kuryeler aracılığıyla ilaçları evlerinize teslim etmek için kullanılır. Jetilaç’ın kullanıcı dostu arayüzü ve güvenlik önlemleri, hastaların kişisel bilgilerinin ve sağlık verilerinin korunmasını sağlar. Tüm işlemler şifreleme protokolleriyle korunur ve gizlilik politikalarına uygun olarak gerçekleştirilir. Jetilaç, yaşlılar, hareket kısıtlılığı olanlar veya yoğun iş temposu nedeniyle eczanelere zaman ayıramayanlar gibi birçok hasta için büyük bir kolaylık sağlar. Aynı zamanda acil durumlar veya önceden belirlenmiş bir zaman dilimi için düzenli ilaç teslimatları gibi özel talepleri de karşılayabilir. Jetilaç, çağdaş teknoloji ve sağlık sektöründeki ihtiyaçlar arasında köprü kurarak hastalara güvenli, hızlı ve kullanıcı dostu bir hizmet sunar. Jetilaç sayesinde, ilaç siparişi vermek ve reçeteleri eczacılara iletmek artık çok daha kolay ve güvenlidir.',
      'pharmacy' : 'Eczane',
      'user login' : 'Kullanıcı girişi',
      'warning' : 'Uyarı',
      'welcome' : 'Hoş Geldiniz!',
      'ifmp' : 'Şifremi Unuttum',
      'siwg' : 'Google ile Giriş Yap',
      'nam' : 'Üye değil misin?',
      'twaeliwg' : 'Google ile giriş yaparken bir hata oluştu.',
      'iuop' : 'Geçersiz kullanıcı adı veya şifre.',
      'lfu' : 'Kullanıcılar İçin Giriş',
      'lfp' : 'Eczacılar İçin Giriş',
      'pfiaf' : 'Lütfen tüm alanları doldurun.',
      'ok' : 'Tamam',
      'neighbourhood' : 'Mahalle',
      'select neighborhood' :'Mahalle Seçin',
      'street' : 'Sokak',
      'enter street name' : 'Sokak Adı Girin',
      'apartment name' : 'Apartman Adı',
      'enter apartment name' : 'Apartman Adı Girin',
      'apartment no' : 'Apartman No',
      'enter apartment number' : 'Apartman No Girin',
      'apartment number' : 'Daire No',
      'eenter apartment number' : 'Daire No Girin',
      'save' : 'Kaydet',
      'peavpn' : 'Lütfen geçerli bir reçete numarası girin (8 haneli olmalı).',
      'peavidn' : 'Lütfen geçerli bir TC kimlik numarası girin (11 haneli olmalı).',
      'psccap' : 'Lütfen şehir, ilçe ve eczane seçimi yapın.',
      'oaai' : 'Sipariş ve Adres Bilgileri',
      'pcyoiitiamiti' : 'Lütfen sipariş bilgilerinizi kontrol ediniz. Bilgilerde yanlışlık varsa önceki sayfaya geri dönerek bilgilerinizi güncelleyiniz.',
      'peyfai' : 'Lütfen tam adres bilginizi giriniz.',
      'cnmbd' : 'Kart numarası 16 haneli olmalıdır',
      'chncbe' : 'Kart sahibi adı boş olamaz!',
      'edcbe' : 'Son kullanma tarihi boş olamaz!',
      'eavedmy' : 'Geçerli bir son kullanma tarihi giriniz (AA/YY)',
      'cvvcbe' : 'CVV boş olamaz!',
      'cvvmbetd' : 'CVV 3 haneli olmalıdır!',
      'yohbsw' : 'Siparişin başarılı bir şekilde gerçekleştirildi.',
      'eapfcblb' : 'E-posta ve şifre alanları boş bırakılamaz.',
      'ahaa' : 'Zaten hesabınız var mı?',
      'petvcstyp' : 'Lütfen telefonunuza gönderilen doğrulama kodunu girin:',
      'pncblb' : 'Telefon numarası boş bırakılamaz!',


    }
  };


}